language: generic
deploy:
  provider: releases
  api_key:
    secure: YM1lLJ+Q/qIELl0ACfPAUo95DZsJY6qGhKbx6DpubwPm/k+EQuwubxzCqhQXVjRUJOIgiQXIoBZAkRXrbbZucVzm3Y24AxZmAv8yloAqrbGUgEnrAPuk5BdW6AcHauW5npc2Rrxu82t/50R0NnO4smhU7Naidht6uAfSkplEx8yxD7MAKKeriL2C1Vf8EPiyt9qJtb5sIdCabh7A0FQxZWaZfnHxJ6ZOxHfEVcpYTXdZCwanIOF1aZNfOmCLFWca1Yg2jzaVl8dYDcZtDA047XhrD/Mja0zV890+ejc1iw6LYIOnH0D6eFLwmSm/SrKKpjWJAA/NZjrcn+mIcWF5UdI+OuKJYYI1yPtC5ovpcCs5tleKSG/FKcyiW7zkpYbJcDbKXQrjUJWb2bJ1GjO+YqC8QsfkkRp3wKWlC4/GMQ+if5FO7fxnoz0mdEHk8PJx5+iwqC3HnEw5ptPQuhjYDJRM2jb2OVu1pAiBkXxDLZ5c8JFYxaezR7eFCkhfGmpp5ze6EQQSbEQtKJYNT/CrB4BJVpa+fRd/4a5V8eaD18OPjBsUaNRda4ujsDs2UB1wuNcuNPCx9JfLzBZpY1XHRV7CyFlOLhP2aJ1CsXRsZoOOPi0u6jIKxEdY7/bC4YQotZMzfxSgaaaCP6l5Q+6nL7T9Rtyu97Ui5Bxok8KUC2Q=
  file: deploy-tomcat7.sh
  on:
    tags: true
    repo: rehei/tomcat7-rehei-deploy

